<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 2 - Sara

The purpose of this document is to generate short stories corresponding to the human-authored corpus using ChatGPT.

## GPT Prompt Design and Text Generation Guidelines

### 1. Prompt design

#### A. Prompt the LLM to extract the plot from the human story

```
=>
0001_plot.txt
```

#### B. Prompt the LLM to provide a style profile for the human story

```
=>
0001_style.txt
----------
```

### 2. Generation

Use the plot and style information below to write a short story.
0001_plot.txt
0001_style.txt

```
=>
0001_llm.txt
...
1000_llm.txt
----------
```

## Required Python packages

- pandas

## Importing the required libraries

In [1]:
import pandas as pd
import os
import sys

## Define input variables

In [2]:
input_directory = 'cl_st1_ph2_sara'
output_directory = 'cl_st1_ph3_sara'
id = 'short_stories'
dataset_filename_1 = f"{id}_sample"

## Create output directory

In [3]:
# Check if the output directory already exists. If it does, do nothing. If it doesn't exist, create it.
if os.path.exists(output_directory):
    print('Output directory already exists.')
else:
    try:
        os.makedirs(output_directory)
        print('Output directory successfully created.')
    except OSError as e:
        print('Failed to create the directory:', e)
        sys.exit(1)

Output directory successfully created.

## Import the data into a DataFrame

In [4]:
df_short_stories_sample_balanced = pd.read_json(f"{input_directory}/{dataset_filename_1}.jsonl", lines=True)

In [5]:
df_short_stories_sample_balanced

,Unnamed: 0,url,length,title,text_no,author,story,valence,arousal,dominance,...,290,291,292,293,294,295,296,297,298,299
0,692,https://americanliterature.com/author/ambrose-...,2478,The Realm Of The Unreal,692,Ambrose Bierce,For a part of the distance between Auburn and ...,0.577191,0.382398,0.570162,...,2.228647,3.891829,-5.375830,2.632187,-1.380860,0.148605,3.219852,0.405671,-0.265541,-6.358305
1,667,https://americanliterature.com/author/ambrose-...,2430,"Parker Adderson, Philosopher",667,Ambrose Bierce,"""Prisoner, what is your name?""\n\n""As I am to ...",0.537938,0.399753,0.546811,...,4.381534,-0.909308,-6.318153,5.111957,3.959732,-2.585404,-3.520969,-2.532245,-6.599809,-1.386203
2,671,https://americanliterature.com/author/ambrose-...,3221,The Affair at Coulter's Notch,671,Ambrose Bierce,"""Do you think, Colonel, that your brave Coulte...",0.536684,0.397451,0.552664,...,6.244731,-4.766285,-2.851505,0.057740,-4.947178,2.573987,-2.322201,2.543712,0.323474,1.143508
3,697,https://americanliterature.com/author/ambrose-...,2883,The Suitable Surroundings,697,Ambrose Bierce,One midsummer night a farmer's boy living abou...,0.581295,0.388130,0.577624,...,-2.911946,-0.908542,-3.546253,-0.625996,2.386898,1.030863,-2.864574,0.376997,-6.561627,0.033366
4,687,https://americanliterature.com/author/ambrose-...,3247,The Middle Toe of the Right Foot,687,Ambrose Bierce,It is well known that the old Manton house is ...,0.567302,0.371715,0.567778,...,4.256649,0.393075,0.440173,-0.864162,-1.034828,-3.147815,-2.177508,-3.916946,-3.065894,-0.515731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,4019,https://americanliterature.com/author/william-...,2753,The Death Of Hanrahan,4025,William Butler Yeats,"Hanrahan, that was never long in one place, wa...",0.594595,0.387619,0.568482,...,-3.786487,-1.089524,-4.052660,3.135613,3.613217,6.796769,6.001264,5.571360,-4.883347,0.652007
999,4020,https://americanliterature.com/author/william-...,2041,The Heart Of The Spring,4026,William Butler Yeats,"A very old man, whose face was almost as flesh...",0.618526,0.371944,0.575418,...,-4.415082,4.553032,-3.704247,-2.860186,-2.718325,-1.277089,2.693682,-5.738874,-0.673790,-1.403249
1000,4022,https://americanliterature.com/author/william-...,2700,The Twisting Of The Rope,4028,William Butler Yeats,Hanrahan was walking the roads one time near K...,0.615338,0.384819,0.587896,...,-0.705627,1.898081,-0.867484,-1.640120,-2.025258,2.516044,4.408704,0.857274,-4.469559,-0.281434
1001,4023,https://americanliterature.com/author/william-...,2388,The Wisdom Of The King,4029,William Butler Yeats,The High-Queen of the Island of Woods had died...,0.601702,0.385151,0.567892,...,-0.588523,-5.461077,-0.784620,3.197701,-0.889868,1.378997,-1.109384,-6.993783,-0.836750,5.936616
1002,4024,https://americanliterature.com/author/william-...,1942,Where There Is Nothing There Is God,4030,William Butler Yeats,"The little wicker houses at Tullagh, where the...",0.588204,0.385218,0.566968,...,-0.153011,-0.887636,-2.591108,-1.385182,2.067777,-4.763770,6.137805,4.166590,-0.664294,-0.203093

### erfsdf

In [6]:
df_short_stories_sample_balanced['file_id'] = 'f' + df_short_stories_sample_balanced.index.astype(str).str.zfill(6)

In [7]:
df_short_stories_sample_balanced

,Unnamed: 0,url,length,title,text_no,author,story,valence,arousal,dominance,...,291,292,293,294,295,296,297,298,299,file_id
0,692,https://americanliterature.com/author/ambrose-...,2478,The Realm Of The Unreal,692,Ambrose Bierce,For a part of the distance between Auburn and ...,0.577191,0.382398,0.570162,...,3.891829,-5.375830,2.632187,-1.380860,0.148605,3.219852,0.405671,-0.265541,-6.358305,f000000
1,667,https://americanliterature.com/author/ambrose-...,2430,"Parker Adderson, Philosopher",667,Ambrose Bierce,"""Prisoner, what is your name?""\n\n""As I am to ...",0.537938,0.399753,0.546811,...,-0.909308,-6.318153,5.111957,3.959732,-2.585404,-3.520969,-2.532245,-6.599809,-1.386203,f000001
2,671,https://americanliterature.com/author/ambrose-...,3221,The Affair at Coulter's Notch,671,Ambrose Bierce,"""Do you think, Colonel, that your brave Coulte...",0.536684,0.397451,0.552664,...,-4.766285,-2.851505,0.057740,-4.947178,2.573987,-2.322201,2.543712,0.323474,1.143508,f000002
3,697,https://americanliterature.com/author/ambrose-...,2883,The Suitable Surroundings,697,Ambrose Bierce,One midsummer night a farmer's boy living abou...,0.581295,0.388130,0.577624,...,-0.908542,-3.546253,-0.625996,2.386898,1.030863,-2.864574,0.376997,-6.561627,0.033366,f000003
4,687,https://americanliterature.com/author/ambrose-...,3247,The Middle Toe of the Right Foot,687,Ambrose Bierce,It is well known that the old Manton house is ...,0.567302,0.371715,0.567778,...,0.393075,0.440173,-0.864162,-1.034828,-3.147815,-2.177508,-3.916946,-3.065894,-0.515731,f000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,4019,https://americanliterature.com/author/william-...,2753,The Death Of Hanrahan,4025,William Butler Yeats,"Hanrahan, that was never long in one place, wa...",0.594595,0.387619,0.568482,...,-1.089524,-4.052660,3.135613,3.613217,6.796769,6.001264,5.571360,-4.883347,0.652007,f000998
999,4020,https://americanliterature.com/author/william-...,2041,The Heart Of The Spring,4026,William Butler Yeats,"A very old man, whose face was almost as flesh...",0.618526,0.371944,0.575418,...,4.553032,-3.704247,-2.860186,-2.718325,-1.277089,2.693682,-5.738874,-0.673790,-1.403249,f000999
1000,4022,https://americanliterature.com/author/william-...,2700,The Twisting Of The Rope,4028,William Butler Yeats,Hanrahan was walking the roads one time near K...,0.615338,0.384819,0.587896,...,1.898081,-0.867484,-1.640120,-2.025258,2.516044,4.408704,0.857274,-4.469559,-0.281434,f001000
1001,4023,https://americanliterature.com/author/william-...,2388,The Wisdom Of The King,4029,William Butler Yeats,The High-Queen of the Island of Woods had died...,0.601702,0.385151,0.567892,...,-5.461077,-0.784620,3.197701,-0.889868,1.378997,-1.109384,-6.993783,-0.836750,5.936616,f001001
1002,4024,https://americanliterature.com/author/william-...,1942,Where There Is Nothing There Is God,4030,William Butler Yeats,"The little wicker houses at Tullagh, where the...",0.588204,0.385218,0.566968,...,-0.887636,-2.591108,-1.385182,2.067777,-4.763770,6.137805,4.166590,-0.664294,-0.203093,f001002

In [8]:
for index, row in df_short_stories_sample_balanced.iterrows():
    # Constructing the file name based on row data and index
    file_name = f"{output_directory}/{row['file_id']}.txt"

    # Writing the 'Short Story Text' content to the file
    with open(file_name, 'w', encoding='utf-8') as file:
        file.write(row['story'])